server:
  port: 8080
  tomcat :
    max-http-form-post-size : 20MB

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: showall
    password: mysql@test
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 2 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: false
    open-in-view: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
     max-request-size: 20MB
     max-file-size: 20MB
